---
name: Docs

on:
  pull_request:

jobs:
  call_workflow:
    uses: cesargoncalves/github-workflows/.github/workflows/terraform-docs.yml@main
    secrets:
      AUTOMATION_PAT: ${{ secrets.AUTOMATION_PAT }}
