---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 1-7 * 6"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  call_workflow:
    uses: cesargoncalves/github-workflows/.github/workflows/renovate.yml@main
