---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  call_workflow:
    uses: cesargoncalves/github-workflows/.github/workflows/renovate.yml@main
    secrets:
      AUTOMATION_PAT: ${{ secrets.AUTOMATION_PAT }}
