---
name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6"

permissions:
  contents: write
  pull-requests: write

jobs:
  call_workflow:
    uses: cesargoncalves/github-workflows/.github/workflows/renovate.yml@main
